export const roomList = [
  {
    id: 1,
    name: "梅の間",
    price: 9800,
    description: "海が一望できる",
    image: "example_1.jpg",
    wifi: false,
    smoking: true,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 20),
      new Date(2024, 7, 21),
      new Date(2024, 7, 22),
    ],
  },
  {
    id: 2,
    name: "竹の間",
    price: 15800,
    description: "山が一望できる",
    image: "example_2.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 25),
      new Date(2024, 7, 26),
      new Date(2024, 7, 27),
    ],
  },
  {
    id: 3,
    name: "松の間",
    price: 19800,
    description: "夕焼けが楽しめる",
    image: "example_3.jpg",
    wifi: true,
    smoking: false,
    breakfast: true,
    reservedDates: [new Date(2024, 7, 1)],
  },
  {
    id: 4,
    name: "鶴の間",
    price: 29800,
    description: "海が一望できる",
    image: "example_4.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 5,
    name: "亀の間",
    price: 19800,
    description: "海が一望できる",
    image: "example_1.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 6,
    name: "富士の間",
    price: 9800,
    description: "富士が一望できる",
    image: "example_2.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 7,
    name: "牡丹の間",
    price: 4800,
    description: "海が一望できる",
    image: "example_3.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 8,
    name: "銀の間",
    price: 12800,
    description: "海が一望できる",
    image: "example_2.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 9,
    name: "金の間",
    price: 16800,
    description: "海が一望できる",
    image: "example_1.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
  {
    id: 10,
    name: "欅の間",
    price: 34800,
    description: "海が一望できる",
    image: "example_4.jpg",
    wifi: true,
    smoking: false,
    breakfast: false,
    reservedDates: [
      new Date(2024, 7, 29),
      new Date(2024, 7, 30),
      new Date(2024, 7, 31),
    ],
  },
];
